export const JOIN_ROOM_CHANNEL = "JOIN_ROOM";
export const ROOM_USERS_CHANNEL = "FETCH_ROOM_USERS";
export const REMOVE_USER_CHANNEL = "REMOVE_USER_FROM_ROOM";
export const SEND_MESSAGE_TO_ROOM_CHANNEL = "SEND_MESSAGE_TO_ROOM";
export const SEND_DIRECT_MESSAGE_CHANNEL = "SEND_DIRECT_MESSAGE";
export const DIRECT_CHAT_CHANNEL = "DIRECT_CHAT";


export const SIGNUP_CHANNEL = "SIGNUP";
export const LOGIN_CHANNEL = "LOGIN";

export const CREATE_ROOM_CHANNEL = "CREATE_ROOM";
export const FETCH_ROOMS_CHANNEL = "FETCH_ROOMS";
export const FETCH_PEOPLE_CHANNEL = "FETCH_PEOPLE";