
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";

export const CONNECT = "CONNECT";
export const CONNECT_SUCCESSFUL = "CONNECT_SUCCESSFUL";
export const CONNECTED_TO_ROOMS_NSC = "CONNECTED_TO_ROOMS_NSC";
export const CONNECTED_TO_CHATROOM_NSC = "CONNECTED_TO_CHATROOM_NSC";

export const LOGOUT = "LOGOUT";

export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const SUBMIT_SIGNUP = "SUBMIT_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const FETCH_PEOPLE = "FETCH_PEOPLE";
export const SET_PEOPLE = "SET_PEOPLE";


export const FETCH_ROOMS = "FETCH_ROOMS";
export const SET_ROOMS = "SET_ROOMS";

export const OPEN_CREATE_ROOM = "OPEN_CREATE_ROOM";
export const CLOSE_CREATE_ROOM = "CLOSE_CREATE_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";
export const CREATE_ROOM_SUCCESSFUL = "CREATE_ROOM_SUCCESSFUL";
export const CREATE_ROOM_FAIL = "CREATE_ROOM_FAIL";

export const JOIN_ROOM = "JOIN_ROOM";
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS";
export const SET_ROOM_USERS = "SET_ROOM_USERS";
export const REMOVE_USER = "REMOVE_USER";

export const SEND_MESSAGE_TO_ROOM = "SEND_MESSAGE_TO_ROOM";
export const NEW_MESSAGE = "NEW_MESSAGE";

export const SEND_DIRECT_MESSAGE = "SEND_DIRECT_MESSAGE";
export const NEW_DIRECT_MESSAGE = "NEW_DIRECT_MESSAGE";

export const DIRECT_CHAT = "DIRECT_CHAT";
export const DIRECT_CHAT_SUCCESS = "DIRECT_CHAT_SUCCESS";
