
export const CONNECT = 'CONNECT';
export const CONNECT_SUCCESSFUL = 'CONNECT_SUCCESSFUL';
export const CONNECTION_CLOSED_OR_FAILED = 'CONNECTION_CLOSED_OR_FAILED';

export const LOGOUT = 'LOGOUT';

export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SUBMIT_SIGNUP = 'SUBMIT_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

