#!/usr/bin/env sh

set -e
export PATH=node_modules/.bin:$PATH

NODE=$(node -v | grep "v7.")

if [ -z "$NODE" ]; then
    echo 'This application is unfortunately not optimised for node versions greater than 7.x'
    echo 'PRs are welcome!'
    exit 1;
else
    echo "starting docker containers.."
fi

echo "⚡️"
docker-compose up -d

echo "containers started ️️️🚀"

npm-run-all --parallel start-db-server start-socket-server start-client